/**
 * Liste de villes françaises utilisée par la détection géographique de
 * l'outil "Termes de recherche". Toutes en minuscules, sans accents
 * (normalisées avec `normalizeText`), y compris les variantes d'écriture
 * courantes (tirets/espaces, abréviations).
 *
 * Couvre les préfectures, sous-préfectures et villes de plus de 30 000
 * habitants, plus les variantes fréquentes dans les requêtes des
 * internautes.
 */
import { normalizeText } from "./csvCore";

export const FRENCH_CITIES: readonly string[] = [
  "paris",
  "marseille",
  "lyon",
  "toulouse",
  "nice",
  "nantes",
  "montpellier",
  "strasbourg",
  "bordeaux",
  "lille",
  "rennes",
  "reims",
  "le havre",
  "saint-etienne",
  "st etienne",
  "sainte etienne",
  "toulon",
  "grenoble",
  "dijon",
  "angers",
  "nimes",
  "villeurbanne",
  "clermont-ferrand",
  "clermont ferrand",
  "le mans",
  "aix-en-provence",
  "aix en provence",
  "aix",
  "brest",
  "tours",
  "amiens",
  "limoges",
  "annecy",
  "perpignan",
  "boulogne-billancourt",
  "boulogne billancourt",
  "metz",
  "besancon",
  "orleans",
  "mulhouse",
  "rouen",
  "caen",
  "nancy",
  "saint-denis",
  "st denis",
  "argenteuil",
  "montreuil",
  "roubaix",
  "tourcoing",
  "avignon",
  "nanterre",
  "creteil",
  "poitiers",
  "versailles",
  "courbevoie",
  "vitry-sur-seine",
  "vitry sur seine",
  "colombes",
  "aulnay-sous-bois",
  "aulnay sous bois",
  "asnieres-sur-seine",
  "asnieres sur seine",
  "asnieres",
  "rueil-malmaison",
  "rueil malmaison",
  "rueil",
  "pau",
  "aubervilliers",
  "champigny-sur-marne",
  "champigny sur marne",
  "antibes",
  "la rochelle",
  "cannes",
  "calais",
  "beziers",
  "colmar",
  "drancy",
  "merignac",
  "saint-nazaire",
  "st nazaire",
  "issy-les-moulineaux",
  "issy les moulineaux",
  "noisy-le-grand",
  "noisy le grand",
  "evry",
  "levallois-perret",
  "levallois perret",
  "levallois",
  "quimper",
  "valence",
  "vannes",
  "troyes",
  "chambery",
  "niort",
  "lorient",
  "sarcelles",
  "villejuif",
  "clichy",
  "hyeres",
  "ajaccio",
  "les abymes",
  "montauban",
  "neuilly-sur-seine",
  "neuilly sur seine",
  "neuilly",
  "sainte-genevieve-des-bois",
  "sainte genevieve des bois",
  "chalon-sur-saone",
  "chalon sur saone",
  "cergy",
  "beauvais",
  "bourges",
  "belfort",
  "meaux",
  "epinay-sur-seine",
  "epinay sur seine",
  "venissieux",
  "la seyne-sur-mer",
  "la seyne sur mer",
  "pessac",
  "clamart",
  "chelles",
  "compiegne",
  "arles",
  "mantes-la-jolie",
  "mantes la jolie",
  "saint-priest",
  "st priest",
  "sartrouville",
  "villeneuve-d'ascq",
  "villeneuve d'ascq",
  "villeneuve dascq",
  "narbonne",
  "franconville",
  "sevran",
  "bondy",
  "castres",
  "la roche-sur-yon",
  "la roche sur yon",
  "fontenay-sous-bois",
  "fontenay sous bois",
  "vincennes",
  "grasse",
  "blois",
  "carcassonne",
  "montlucon",
  "chartres",
  "cholet",
  "saint-quentin",
  "st quentin",
  "albi",
  "salon-de-provence",
  "salon de provence",
  "saint-malo",
  "st malo",
  "annemasse",
  "bourg-en-bresse",
  "bourg en bresse",
  "macon",
  "charleville-mezieres",
  "charleville mezieres",
  "laval",
  "evreux",
  "saint-brieuc",
  "st brieuc",
  "cergy-pontoise",
  "cergy pontoise",
  "chateauroux",
  "vichy",
  "tarbes",
  "brive-la-gaillarde",
  "brive la gaillarde",
  "brive",
  "auxerre",
  "libourne",
  "roanne",
  "angouleme",
  "arras",
  "dunkerque",
  "saint-omer",
  "st omer",
  "epinal",
  "thionville",
  "haguenau",
  "vesoul",
  "lons-le-saunier",
  "lons le saunier",
  "moulins",
  "gap",
  "digne-les-bains",
  "digne les bains",
  "digne",
  "privas",
  "aurillac",
  "rodez",
  "mende",
  "foix",
  "cahors",
  "agen",
  "auch",
  "mont-de-marsan",
  "mont de marsan",
  "gueret",
  "nevers",
  "chaumont",
  "bar-le-duc",
  "bar le duc",
  "verdun",
  "saint-lo",
  "st lo",
  "alencon",
  "laon",
  "soissons",
  "peronne",
  "abbeville",
  "avranches",
  "cherbourg",
  "cherbourg-en-cotentin",
  "cherbourg en cotentin",
  "granville",
  "lisieux",
  "bayeux",
  "vire",
  "flers",
  "argentan",
  "domfront",
  "mamers",
  "sable-sur-sarthe",
  "sable sur sarthe",
  "la fleche",
  "saumur",
  "chinon",
  "loches",
  "amboise",
  "vendome",
  "romorantin-lanthenay",
  "romorantin",
  "montargis",
  "pithiviers",
  "gien",
  "sens",
  "joigny",
  "avallon",
  "tonnerre",
  "dole",
  "gray",
  "pontarlier",
  "montbeliard",
  "altkirch",
  "guebwiller",
  "thann",
  "saverne",
  "molsheim",
  "wissembourg",
  "sarreguemines",
  "forbach",
  "sarrebourg",
  "chateau-thierry",
  "chateau thierry",
  "saint-dizier",
  "st dizier",
  "sedan",
  "rethel",
  "vitry-le-francois",
  "vitry le francois",
  "langres",
  "saint-die-des-vosges",
  "saint die des vosges",
  "saint die",
  "remiremont",
  "lure",
  "pontivy",
  "lannion",
  "guingamp",
  "dinan",
  "morlaix",
  "concarneau",
  "quimperle",
  "douarnenez",
  "chateaulin",
  "redon",
  "fougeres",
  "vitre",
  "coutances",
  "valognes",
  "carentan",
  "mayenne",
  "chateau-gontier",
  "chateau gontier",
  "segre",
  "les sables-d'olonne",
  "les sables d'olonne",
  "les sables dolonne",
  "fontenay-le-comte",
  "fontenay le comte",
  "lucon",
  "challans",
  "parthenay",
  "bressuire",
  "thouars",
  "civray",
  "confolens",
  "cognac",
  "saintes",
  "royan",
  "rochefort",
  "jonzac",
  "marennes",
  "bergerac",
  "perigueux",
  "sarlat-la-caneda",
  "sarlat",
  "nontron",
  "montmorillon",
  "chatellerault",
  "loudun",
  "villefranche-sur-saone",
  "villefranche sur saone",
  "tarare",
  "vienne",
  "bourgoin-jallieu",
  "bourgoin jallieu",
  "thiers",
  "riom",
  "issoire",
  "ambert",
  "le puy-en-velay",
  "le puy en velay",
  "le puy",
  "yssingeaux",
  "brioude",
  "aubenas",
  "tournon-sur-rhone",
  "tournon sur rhone",
  "annonay",
  "romans-sur-isere",
  "romans sur isere",
  "montelimar",
  "die",
  "nyons",
  // Note : "orange" (Vaucluse) est volontairement exclue de cette liste.
  // C'est aussi un nom commun très fréquent ("jus d'orange", "orange
  // pressée"...) : l'inclure produirait trop de faux positifs en
  // détection géographique. Un utilisateur qui cible réellement Orange
  // peut toujours l'ajouter à ses propres zones autorisées si besoin.
  "carpentras",
  "cavaillon",
  "apt",
  "manosque",
  "sisteron",
  "briancon",
  "embrun",
  "barcelonnette",
  "draguignan",
  "brignoles",
  "saint-raphael",
  "st raphael",
  "frejus",
  "menton",
  "vence",
  "cagnes-sur-mer",
  "cagnes sur mer",
  "sophia-antipolis",
  "sophia antipolis",
  "sete",
  "lunel",
  "ales",
  "bagnols-sur-ceze",
  "bagnols sur ceze",
  "uzes",
  "le vigan",
  "millau",
  "villefranche-de-rouergue",
  "villefranche de rouergue",
  "mazamet",
  "gaillac",
  "graulhet",
  "lavaur",
  "revel",
  "muret",
  "saint-gaudens",
  "st gaudens",
  "bagneres-de-bigorre",
  "bagneres de bigorre",
  "lourdes",
  "oloron-sainte-marie",
  "oloron sainte marie",
  "bayonne",
  "biarritz",
  "anglet",
  "hendaye",
  "saint-jean-de-luz",
  "saint jean de luz",
  "dax",
  "villeneuve-sur-lot",
  "villeneuve sur lot",
  "marmande",
  "langon",
  "arcachon",
  "andernos-les-bains",
  "andernos les bains",
  "lacanau",
  "blaye",
  "coutras",
] as const;

/**
 * Certaines villes ont plusieurs mots (ex. "saint etienne", "le havre").
 * On les garde telles quelles ; la détection dans `searchParser.ts` gère
 * le multi-mots via une correspondance de sous-séquence sur les mots du
 * terme, avec limites de mots (pas de sous-chaîne brute).
 */
export function isKnownCity(candidate: string): boolean {
  return FRENCH_CITIES.includes(candidate);
}

/** Découpe un texte normalisé en mots (limites = tout ce qui n'est pas alphanumérique). */
function tokenize(text: string): string[] {
  return text.split(/[^a-z0-9]+/).filter(Boolean);
}

// Villes triées par nombre de mots décroissant : on teste d'abord les
// correspondances multi-mots ("saint etienne") avant les mono-mots, pour
// ne pas s'arrêter trop tôt sur un sous-ensemble.
const CITIES_BY_WORD_COUNT = [...FRENCH_CITIES]
  .map((city) => ({ city, words: tokenize(city) }))
  .sort((a, b) => b.words.length - a.words.length);

/**
 * Cherche une ville connue dans un texte libre, en comparant des mots
 * entiers (jamais une sous-chaîne brute) : "pau" ne matche pas dans
 * "paupiette", "st etienne" matche dans "hotel st etienne centre".
 * Retourne la ville détectée (telle qu'écrite dans `FRENCH_CITIES`), ou
 * `undefined` si aucune ville n'est trouvée.
 */
export function findCityInText(text: string): string | undefined {
  const words = tokenize(normalizeText(text));
  if (words.length === 0) return undefined;

  for (const { city, words: cityWords } of CITIES_BY_WORD_COUNT) {
    for (let i = 0; i <= words.length - cityWords.length; i++) {
      if (cityWords.every((word, offset) => words[i + offset] === word)) {
        return city;
      }
    }
  }
  return undefined;
}

/**
 * Compare une ville détectée à une zone autorisée saisie par l'utilisateur,
 * dans les deux sens : "paris" saisi doit matcher "paris 15", et
 * "paris 15" saisi doit matcher un terme qui contient juste "paris".
 */
export function zoneMatchesCity(zone: string, city: string): boolean {
  const normalizedZone = normalizeText(zone);
  if (!normalizedZone) return false;
  const zoneWords = tokenize(normalizedZone);
  const cityWords = tokenize(city);
  const zoneContainsCity = cityWords.every((word) => zoneWords.includes(word));
  const cityContainsZone = zoneWords.every((word) => cityWords.includes(word));
  return zoneContainsCity || cityContainsZone;
}

/**
 * Une ville détectée est "hors zone" (donc à exclure) si aucune des zones
 * autorisées saisies par l'utilisateur ne la couvre. Si la liste de zones
 * est vide, la détection géographique est désactivée : on retourne `true`
 * (couverte) pour ne jamais classer un terme en `geo` sans zones saisies.
 */
export function isCityOutsideAllowedZones(city: string, allowedZones: string[]): boolean {
  if (allowedZones.length === 0) return false;
  return !allowedZones.some((zone) => zoneMatchesCity(zone, city));
}
